### PR TITLE
add calculator and ignore .idea map

### PR DESCRIPTION
**Pull request by tommie1001**
Added an html snippit which functions as a calculator. Nothing to fancy but perhaps a cool startup snippit for html/js beginners!

### CODE REVIEW

**Comment by zyyyxptrr** [comment]
Hello, please provide an explanation of the code you sent.

for example :

`this is example design pattern in PHP`

So that we know the function of the code you sent

**Comment by zyyyxptrr** [comment]
We are preparing this repo. please upload the code in the ```code``` folder according to the available language category. if language is not available, please open our [issue](https://github.com/gemarkode/Codebase/issues/30).

**Comment by tommie1001** [comment]
Hi i added an calculator build with html jquery and css. Nothing to special, but thought it would be a fun snippit in you're codebase

**Review by rizkytegar — APPROVED** [review]

**Comment by rizkytegar** [comment]
thank you for contributing.

Happy Hacktoberfest ❤️

**Pull request merged**
